# -*- coding: utf-8 -*-
"""Script_Combine_files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByN2nm5n6zbMXraubcrwgnMand1H8hgS
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import os

all_data = []

for filename in os.listdir():
    if filename.startswith('data-'):  # adjust if files have different names
        df = pd.read_csv(filename, sep="\t", header=None, names=['Date', 'Time', 'Code', 'Value'])
        df['SourceFile'] = filename
        all_data.append(df)

# Combine all
combined_df = pd.concat(all_data, ignore_index=True)

# Save to CSV
combined_df.to_csv("Diabetes_combined_data.csv", index=False)

files.download("Diabetes_combined_data.csv")















